// Three.js export adapter mapping to standard Three.js naming
import {
  M as Matrix4,
  V as Vector3,
  Q as Quaternion,
  O as Object3D,
  B as BoxGeometry,
  W as WebGLRenderer,
  P as PCFSoftShadowMap,
  A as ACESFilmicToneMapping,
  S as Scene,
  C as Color,
  F as FogExp2,
  a as PerspectiveCamera,
  b as MeshStandardMaterial,
  H as HemisphereLight,
  c as SpotLight,
  D as DirectionalLight,
  d as PointLight,
  R as RepeatWrapping,
  G as Group,
  e as Mesh,
  f as CylinderGeometry,
  g as DoubleSide,
  h as ConeGeometry,
  T as TorusGeometry,
  i as PlaneGeometry,
  j as MeshBasicMaterial,
  k as BufferGeometry,
  l as Float32BufferAttribute,
  m as Points,
  n as PointsMaterial,
  o as CanvasTexture,
  p as SRGBColorSpace,
  q as Vector2,
  r as Raycaster,
  s as MathUtils
} from '../assets/three.js';

export {
  Matrix4,
  Vector3,
  Quaternion,
  Object3D,
  BoxGeometry,
  WebGLRenderer,
  PCFSoftShadowMap,
  ACESFilmicToneMapping,
  Scene,
  Color,
  FogExp2,
  PerspectiveCamera,
  MeshStandardMaterial,
  HemisphereLight,
  SpotLight,
  DirectionalLight,
  PointLight,
  RepeatWrapping,
  Group,
  Mesh,
  CylinderGeometry,
  DoubleSide,
  ConeGeometry,
  TorusGeometry,
  PlaneGeometry,
  MeshBasicMaterial,
  BufferGeometry,
  Float32BufferAttribute,
  Points,
  PointsMaterial,
  CanvasTexture,
  SRGBColorSpace,
  Vector2,
  Raycaster,
  MathUtils
};
